name: electron-app
version: '1.0.0'
summary: App summary
description: |
  App description

grade: devel
confinement: devmode

parts:
  electron-app:
    plugin: nil
    stage-packages:
    - libgconf2-4
    - libnotify4
    - libnss3
    - libpcre3
    - libxss1
    - libxtst6
    after:
    - desktop-gtk2
    - desktop-gtk3
